//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTrade.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class АвтосалонEntities : DbContext
    {
        public АвтосалонEntities()
            : base("name=АвтосалонEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Автомобили> Автомобили { get; set; }
        public virtual DbSet<Должности> Должности { get; set; }
        public virtual DbSet<Дополнительное_оборудование> Дополнительное_оборудование { get; set; }
        public virtual DbSet<Заказчики> Заказчики { get; set; }
        public virtual DbSet<Производители> Производители { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Тип_кузова> Тип_кузова { get; set; }
    }
}
