//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказчики
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказчики()
        {
            this.Автомобили = new HashSet<Автомобили>();
        }
    
        public int Код_заказчика { get; set; }
        public string ФИО { get; set; }
        public string Адрес { get; set; }
        public string Телефон { get; set; }
        public string Паспортные_данные { get; set; }
        public Nullable<System.DateTime> Дата_заказа { get; set; }
        public Nullable<System.DateTime> Дата_продажи { get; set; }
        public byte[] Отметка_о_выполнении { get; set; }
        public byte[] Отметка_об_оплате { get; set; }
        public Nullable<int> Процент_предоплаты { get; set; }
        public int Код_сотрудника { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Автомобили> Автомобили { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
